### PR TITLE
Declarative syntax with function builder

### PR DESCRIPTION
**Pull request by ra1028**
# This is WIP Until Xcode GM is released.

close https://github.com/ra1028/Carbon/issues/35

## Checklist
- [x] All tests are passed.  
- [x] Added tests.  
- [x] Documented the code using [Xcode markup](https://developer.apple.com/library/mac/documentation/Xcode/Reference/xcode_markup_formatting_ref).  
- [x] Searched [existing pull requests](https://github.com/ra1028/Carbon/pulls) for ensure not duplicated.  

## Description

Add support declarative syntax like SwiftUI with function builder for Swift5.1.

```swift
renderer.render {
    Label("foo")
    Label("bar")
    Label("baz")

    if flag {
        Label("qux")
    }
}
```
```swift
renderer.render {
    Section(id: "section1") {
        Label("foo")
        Label("bar")
        Label("baz")
    }

    Section(
        id: "section2",
        header: Label("header"),
        footer: Label("footer"),
        cells: {
            Label("qux")
            
            if flag {
                Label("quux")
            }
        }
    )
}
```

## Related Issue

https://github.com/ra1028/Carbon/issues/35

## Motivation and Context
See related issues and description.

### CODE REVIEW

**Comment by Zasuk** [comment]
do you think it is possible to add something like: https://github.com/simonmitchell/ClosureView

right now i'm using some switch statements with the old builder function

**Comment by ra1028** [comment]
Possible.
However, Carbon decided not to support it for some reasons such as SwiftUI doesn't support it and type-erasure is required.
You can implement it using `CellsBuildable` or` SectionsBuildable`.
Anyway, hope that future Swift will support switch statement.

**Comment by Zasuk** [comment]
i'll adapt the code to don't use it...it it make it easy to upgrade to latest Carbon versions

i'm in the middle of migration to this new function builder

**Comment by Zasuk** [comment]
@ra1028 
can you give some technical explanation why it is limited to 10 items?
it isn't a problem but i'm curious to know why it was designed like this

**Comment by ra1028** [comment]
Elements are built by compiler magic as generic parameters as here.
https://github.com/ra1028/Carbon/blob/ba15f1eb973339409c9e7640bf53b6f35d1537e7/Sources/FunctionBuilder/CellsBuilder.swift
The number of 10 doesn't have a reasonable meaning, but matches with spec of SwiftUI ViewBuilder.
And, like SwiftUI, you can get around that limitation with `Group`.
```swift
renderer.render {
    Label("1")
    Label("2")
    Label("3")
    Label("4")
    Label("5")
    Label("6")
    Label("7")
    Label("8")
    Label("9")
    Group {
        Label("10")
        Label("11")
        Label("12")
    }
}
```

**Pull request merged**
